name: Build & deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 13.x

            - name: Install NPM packages
              run: yarn install

            - name: Build Project
              run: yarn build-prod

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: gh-pages # The branch the action should deploy to.
                  folder: build # The folder the action should deploy.
